spring:
  application:
    name: course-catalog-service
  datasource:
    url: jdbc:mysql://localhost:3306/bm?autoreconnect=true
    username: root
    password: root
  flyway:
    url: jdbc:mysql://localhost:3306/bm
    locations: classpath:/db/migration
    user: root
    password: root

MESSAGE: Welcome Onboard !
